Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/StringLiteral:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false 

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false
